<a href="https://colab.research.google.com/github/aledash3/NumPy/blob/main/IA_Taller_numpy_CruzDavid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Taller de Numpy***

Autor: David Cruz

Fecha: 16/04/2026

##Listas
--------


In [ ]:
numeros = [10,20,30,40,50]
mixta = [1, "Texto", 3.141516, True]
vacia = []
de_rango = list(range(1,10))

Acceso por índice

In [ ]:
print(numeros[0])
print(numeros[-1])
print(numeros[-5])

10
50
10


Slicing [inicio:fin:paso]

In [ ]:
print(numeros[1:4])
print(numeros[:3]) #desde el inicio hasta el indice
print(numeros[3:]) #desde el indice N hasta el final (3...)
print(numeros[::2]) #salto
print(numeros[::-1]) #invertir lista

[20, 30, 40]
[10, 20, 30]
[40, 50, 60]
[10, 30, 50]
[60, 50, 40, 30, 20, 10]


Métodos principales

In [ ]:
numeros.append(60) #agrega al final de la lista O(1)
numeros.insert(2,99) #agrega al inicio de la lista O(n)
numeros.remove(99)
print(numeros)
numeros.pop()
print(len(numeros))

[10, 20, 30, 40, 50, 60, 60, 60, 60, 60]
9


List Comprehensions

In [ ]:
cuadrados = [x**2 for x in range(1,9)]
pares = [x for x in range(1,21) if x % 2 ==0]
print(cuadrados)
print(pares)


[10, 20, 30, 40, 50, 60, 60, 60, 60]
[1, 4, 9, 16, 25, 36, 49, 64]


Comprehension anidada (matriz)

In [ ]:
tabla = [[i * j for j in range(1,5)] for i in range(1,4)]
print(table)



Transformacion de Tipo

In [ ]:
palabras = ['hola', 'MUNDO', 'Python']
minusculas = [w.lower() for w in palabras]
# ['hola', 'mundo', 'python']
print(minusculas)

['hola', 'mundo', 'python']


***TUPLAS***

Creación

In [ ]:
coordenada = (3.5, -1.2) # tupla de 2 elementos
dimensiones = (28, 28, 3) # alto, ancho, canales (imagen RGB)
unitaria = (42,) # IMPORTANTE: la coma crea la tupla
no_tupla = (42) # esto es sólo el entero 42
print(coordenada)
print(dimensiones)
print(unitaria)
print(no_tupla, type(no_tupla))


(3.5, -1.2)
(28, 28, 3)
(42,)
42 <class 'int'>


Acceso

In [ ]:
print(dimensiones[0])
print(dimensiones[-1])

28
3


Desempaquetado (Unpacking)

In [ ]:
x,y = coordenada
alto, ancho, profundidad = dimensiones
print(x, y, alto, ancho, profundidad)

3.5 -1.2 28 28 3


Las Tuplas son inmutable

In [ ]:
dimensiones[0] = 35 #ESto genera error

***DICCIONARIOS***

Creación

In [ ]:
estudiante = {
'nombre': 'María',
'edad': 22,
'notas': [8.5, 9.0, 7.5],
'activo': True
}
print(estudiante)

{'nombre': 'María', 'edad': 22, 'notas': [8.5, 9.0, 7.5], 'activo': True}


Acceso

In [ ]:
print(estudiante["nombre"])
print(estudiante.get("carrera", "N/A"))


María
N/A


Modificación

In [ ]:
estudiante['edad'] = 23 # modifica valor existente
estudiante['semestre'] = 6 # agrega nueva clave y valor

Iteración

In [ ]:
for clave, valor in estudiante.items():
  print(f'{clave:12s} → {valor}')

nombre       → María
edad         → 22
notas        → [8.5, 9.0, 7.5]
activo       → True


Dict Comprehension

In [ ]:
cubos = {x: x**3 for x in range(1, 6)}
for i in cubos:
  print(f'{i:2d} → {cubos[i]}')

# {1:1, 2:4, 3:9, 4:16, 5:25}

 1 → 1
 2 → 8
 3 → 27
 4 → 64
 5 → 125


Otros métodos

In [ ]:
elementos = list(estudiante.values())
print(elementos, type(elementos))



['María', 22, [8.5, 9.0, 7.5], True] <class 'list'>


Verificar existencia de clave

In [ ]:
if 'nombre' in estudiante:
    print('La clave existe')

La clave existe


***Funciones***

 Función básica

In [ ]:
def saludar(nombre):
    return f'Hola, {nombre}!'

 Con parámetros por defecto

In [ ]:
def potencia(base, exponente=2):
    '''Eleva base a exponente. Por defecto calcula el cuadrado.'''
    return base ** exponente
print(potencia(5))      # 25  (usa exponente=2 por defecto)
print(potencia(2, 10))  # 1024

25
1024


Retorno múltiple (devuelve una tupla)

In [ ]:
def min_max(lista):
    return min(lista), max(lista)      # empaqueta como tupla

minimo, maximo = min_max([3,1,7,2,5]) # desempaqueta
print(minimo, maximo)

1 7


Lambda — función anónima

In [ ]:
doble = lambda x: x * 2
print(doble(8))   # 16
# Útil como argumento en funciones de orden superior
nums = [5, 2, 8, 1, 9, 3]
ordenados = sorted(nums, key=lambda x: -x)  # orden descendente
# [9, 8, 5, 3, 2, 1]

16


map y filter

In [ ]:
cuadrados = list(map(lambda x: x**2, nums))
mayores   = list(filter(lambda x: x > 4, nums))


# ¿Qué es NumPy y por qué es diferente?

2.2  Creación de Arrays

# Comparativa: Listas de Python vs. Arrays de NumPy

Es fundamental entender por qué usamos NumPy en lugar de listas estándar cuando trabajamos con grandes volúmenes de datos.

---

### 1. Tabla Comparativa de Rendimiento y Estructura

| Característica | Lista de Python | Array de NumPy (`ndarray`) |
| :--- | :--- | :--- |
| **Tipos de datos** | Heterogéneos (pueden mezclar tipos) | **Un solo tipo (`dtype`)** |
| **Almacenamiento** | Objetos dispersos en memoria | **Bytes contiguos** (más eficiente) |
| **Operaciones** | No permite matemáticas directas | **Aritmética elemento a elemento** |
| **Bucle / Loop** | Necesario para operar cada dato | **Vectorización automática** |
| **Memoria** | Fragmentada | **Memoria contigua** (cache-friendly) |
| **Velocidad** | Lenta para cálculo científico | **Base del ecosistema de Datos** |

---

### 2. Conceptos Clave de Eficiencia

#### 🧠 Memoria Contigua
A diferencia de las listas de Python, donde cada elemento es un objeto que puede estar en cualquier parte de la memoria, los arrays de NumPy guardan los datos uno junto al otro. Esto permite que el procesador los lea mucho más rápido.

#### ⚡ Vectorización
NumPy permite realizar operaciones en todo el array sin necesidad de escribir un bucle `for`.
* **Ejemplo:** `mi_array * 2` multiplica todos los elementos instantáneamente.



---

### 3. Recordatorio de Propiedades de Creación
* **Upcasting:** Si mezclas `int` y `float`, todo sube a `float64`.
* **Coerción:** Si hay un `string`, todo se vuelve `string`.
* **Optimización:** Puedes usar `dtype=np.int32` o `dtype=np.float32` para que el archivo pese menos.

# NumPy: Fundamentos de `np.array()`

El constructor principal `np.array()` permite transformar listas de Python en objetos **ndarray**, optimizados para cálculos numéricos.

---

### 1. Inferencia de Datos y Upcasting
NumPy asigna automáticamente el tipo de dato (`dtype`) analizando el contenido de la lista:

* **Detección Automática:**
    * Si todos los elementos son **enteros** $\rightarrow$ `int64`.
    * Si hay al menos un **decimal** $\rightarrow$ `float64`.
* **Upcasting Automático:** Al mezclar `int` y `float`, todos los elementos se promueven a **`float64`** por ser el de mayor precisión.



---

### 2. Mezcla con Strings (Cadenas)
La presencia de texto domina sobre los números en la jerarquía de tipos:
* Si la lista contiene al menos un **string**, todos los elementos se convierten a **Unicode string** (`<U...`).

---

### 3. Parámetro `dtype`: Forzado de Tipos
Puedes usar el parámetro opcional `dtype` para controlar manualmente el tipo de dato y optimizar la memoria:

| Parámetro | Descripción | Caso de Uso |
| :--- | :--- | :--- |
| `dtype=np.float32` | Ocupa 4 bytes por elemento. | Ahorra el 50% de memoria comparado con `float64`. |
| `dtype=np.int32` | Enteros de 32 bits. | Ideal para datasets grandes donde no necesitas `int64`. |
| `dtype=bool` | Convierte a **booleano**. | `0` es `False`, cualquier otro número es `True`. |

In [ ]:
import numpy as np

# ── Array 1-D (vector) ─────────────────────────────────────────────
v = np.array([10, 20, 30, 40, 50])
print(v)          # [10 20 30 40 50]
print(type(v))    # <class 'numpy.ndarray'>
print(v.dtype)    # int64

# ── Array 2-D (matriz) ─────────────────────────────────────────────
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# ── Upcasting automático ───────────────────────────────────────────
mix = np.array([1, 2, 3.0])    # int + float → float64
print(mix.dtype)               # float64

# ── Forzar tipo de dato ─────────────────────────────────────────────
float32 = np.array([1, 2, 3], dtype=np.float32)
booleano = np.array([0, 1, 0, 1], dtype=bool)
print(float32.dtype)   # float32
print(booleano)        # [False  True False  True]

2.2.2  Funciones de Creación Especializadas

# Funciones para Crear Arrays en NumPy

Además de `np.array()`, NumPy ofrece funciones especializadas para generar arrays con valores específicos o secuencias numéricas.

---

### 1. Arrays con Valores Constantes
| Función | Descripción |
| :--- | :--- |
| `np.zeros(shape)` | Crea un array de ceros. Por defecto el tipo es `float64`. |
| `np.ones(shape)` | Crea un array relleno de unos ($1.0$). |
| `np.full(shape, valor)` | Crea un array donde todos los elementos tienen el valor especificado. |
| `np.eye(n)` | Genera una **matriz identidad** de $n \times n$ (1 en la diagonal principal). |

---

### 2. Secuencias Numéricas
| Función | Descripción |
| :--- | :--- |
| `np.arange(start, stop, step)` | Similar a `range()`. El extremo `stop` queda **EXCLUIDO**. |
| `np.linspace(start, stop, n)` | Genera $n$ valores **igualmente espaciados**. El extremo `stop` queda **INCLUIDO**. |

---

### 3. Generación de Números Aleatorios (`np.random`)
Estas funciones son esenciales para simulaciones y modelos de Machine Learning.

* **`np.random.seed(n)`**: Fija una semilla para que los valores aleatorios sean **reproducibles** (siempre salgan los mismos al ejecutar de nuevo).
* **`np.random.rand(d0, d1, ...)`**: Distribución uniforme en el intervalo $[0, 1)$.
* **`np.random.randn(d0, d1, ...)`**: Distribución **normal estándar** (media 0, desviación 1).
* **`np.random.randint(low, high, size)`**: Enteros aleatorios donde el valor `high` queda **EXCLUIDO**.

---

In [ ]:
import numpy as np

# ── Arrays de ceros y unos ─────────────────────────────────────────
ceros  = np.zeros((3, 4))     # matriz 3x4 de 0.0
unos   = np.ones((2, 5))      # matriz 2x5 de 1.0
print(ceros.shape)            # (3, 4)

# ── Identidad ──────────────────────────────────────────────────────
I = np.eye(4)                 # 4x4: 1 en diagonal, 0 fuera
print(I)

# ── arange vs linspace ─────────────────────────────────────────────
# arange: define el PASO
a = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]  — stop 10 excluido
# linspace: define la CANTIDAD de puntos
b = np.linspace(0, 1, 5)      # [0.   0.25  0.5   0.75  1. ]  — stop incluido

print('arange:  ', a)
print('linspace:', b)

# ── Aleatorios ─────────────────────────────────────────────────────
np.random.seed(42)            # semilla fija → reproducible
uniforme = np.random.rand(3, 4)    # valores entre [0,1)
normal   = np.random.randn(3, 4)   # distribución normal (μ=0, σ=1)
enteros  = np.random.randint(1, 10, size=(3, 3))  # enteros en [1, 10)

print(enteros)

(3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2.3  Atributos del ndarray

# 📊 Atributos Principales de un Array en NumPy

Una vez creado un array, podemos consultar sus propiedades internas (atributos) para entender su estructura y consumo de memoria.

---

### 1. Estructura y Dimensiones
| Atributo | Tipo / Valor | Descripción |
| :--- | :--- | :--- |
| **`.shape`** | `tuple` | Dimensiones del array. Ej: `(3, 4)` para 3 filas y 4 columnas. |
| **`.ndim`** | `int` | Número de dimensiones (ejes). 1: vector, 2: matriz, 3+: tensor. |
| **`.size`** | `int` | Número total de elementos (producto de los valores de `.shape`). |

---

### 2. Tipos de Datos y Memoria
| Atributo | Tipo / Valor | Descripción |
| :--- | :--- | :--- |
| **`.dtype`** | `dtype` | Tipo de dato de los elementos (ej: `int64`, `float32`, `bool`). |
| **`.itemsize`** | `int` (bytes) | Tamaño en bytes de **un solo elemento**. (Ej: `float64` = 8 bytes). |
| **`.nbytes`** | `int` (bytes) | Memoria total que ocupa el array (`size` $\times$ `itemsize`). |

---

### 3. Transformaciones Rápidas
* **`.T`**: Devuelve la **transpuesta** del array. Intercambia filas por columnas (muy útil en matrices 2D).

---

In [ ]:
import numpy as np

A = np.random.randint(0, 100, size=(4, 3, 2))   # tensor 3-D

print('shape:    ', A.shape)      # (4, 3, 2)
print('ndim:     ', A.ndim)       # 3
print('size:     ', A.size)       # 24  (4×3×2)
print('dtype:    ', A.dtype)      # int64
print('itemsize: ', A.itemsize)   # 8 bytes por elemento
print('nbytes:   ', A.nbytes)     # 192 bytes en total

# ── Diferencia entre shape de vector y matriz ──────────────────────
v = np.array([1, 2, 3, 4, 5])
M = np.array([[1, 2, 3, 4, 5]])

print(v.shape)   # (5,)    → vector 1-D con 5 elementos
print(M.shape)   # (1, 5)  → matriz 2-D de 1 fila y 5 columnas
# Son numéricamente equivalentes pero estructuralmente distintos

3.1  Indexing — Acceso a Elementos

In [ ]:
import numpy as np

M = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

# ── Acceso a elementos individuales ────────────────────────────────
print(M[0, 0])    # 10  → fila 0, columna 0
print(M[1, 2])    # 60  → fila 1, columna 2
print(M[-1, -1])  # 90  → última fila, última columna

# ── Acceso a filas y columnas completas ────────────────────────────
# ':' en un eje significa 'todos los elementos de ese eje'
print(M[0, :])    # [10 20 30]  → fila 0 completa
print(M[:, 1])    # [20 50 80]  → columna 1 completa
print(M[-1, :])   # [70 80 90]  → última fila

# ── Tensor 3-D ─────────────────────────────────────────────────────
T = np.arange(24).reshape(2, 3, 4)  # 2 'páginas', 3 filas, 4 columnas
print(T[0])            # primera 'página' (matriz 3×4)
print(T[1, 2, 3])      # página 1, fila 2, columna 3
print(T[:, 0, :])      # primera fila de TODAS las páginas

3.2  Slicing — Selección de Subconjuntos

In [ ]:
import numpy as np

A = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

# ── Slicing básico ─────────────────────────────────────────────────
# [fila_ini:fila_fin , col_ini:col_fin]
sub = A[0:2, 1:3]       # filas 0-1, columnas 1-2
print(sub)
# [[ 2  3]
#  [ 6  7]]

# ── Omitir índices ─────────────────────────────────────────────────
print(A[:2, :])    # primeras 2 filas completas
print(A[1:, 2:])   # desde fila 1, desde columna 2

# ── Con paso ────────────────────────────────────────────────────────
print(A[::2, ::2])  # filas pares, columnas pares
# [[ 1  3]
#  [ 9 11]]

# ── Vista vs. Copia ────────────────────────────────────────────────
vista = A[0, :]          # es una vista
copia = A[0, :].copy()   # es una copia independiente

vista[0] = 999           # modifica A también!
copia[0] = 888           # NO modifica A

print(A[0, :])   # [999   2   3   4] ← vista modificó el original
print(np.shares_memory(A, vista))   # True
print(np.shares_memory(A, copia))   # False

3.3  Indexación Booleana (Boolean Masking)

In [ ]:
import numpy as np

datos = np.array([[5, 12, 3, 18],
                  [7,  2, 15, 9],
                  [11, 6, 20, 1]])

# ── Crear máscara booleana ──────────────────────────────────────────
mascara = datos > 10          # array de True/False con misma shape
print(mascara)
# [[False  True False  True]
#  [False False  True False]
#  [ True False  True False]]

# ── Aplicar máscara (filtro) ────────────────────────────────────────
mayores = datos[mascara]      # devuelve 1-D con los valores True
print(mayores)   # [12 18 15 11 20]

# ── Combinación de condiciones ─────────────────────────────────────
# Valores entre 5 y 15 (inclusive)
rango = datos[(datos >= 5) & (datos <= 15)]
print(rango)    # [ 5 12  7 15  9 11  6]

# ── Modificar elementos con máscara ────────────────────────────────
copia = datos.copy()
copia[copia < 5] = 0    # reemplaza valores menores a 5 con 0
print(copia)

# ── np.where — condicional vectorizado ─────────────────────────────
# np.where(cond, valor_si_True, valor_si_False)
resultado = np.where(datos > 10, datos, 0)   # deja >10, reemplaza resto con 0
print(resultado)

3.4  Fancy Indexing

In [ ]:
import numpy as np
M = np.array([[10, 11, 12],
              [20, 21, 22],
              [30, 31, 32],
              [40, 41, 42]])

# ── Selección de filas por índice ──────────────────────────────────
indices = [0, 2, 3]
print(M[indices])       # filas 0, 2 y 3
# [[10 11 12]
#  [30 31 32]
#  [40 41 42]]

# ── Selección en orden arbitrario (incluso repetido) ───────────────
print(M[[3, 1, 3, 0]])  # fila 3, luego 1, luego 3 otra vez, luego 0

# ── Combinación con slicing ─────────────────────────────────────────
print(M[[0, 2], 1:])    # filas 0 y 2, columnas desde la 1
# [[11 12]
#  [31 32]]

# ── Fancy indexing de columnas ─────────────────────────────────────
cols = [2, 0]
print(M[:, cols])       # columnas 2 y 0 (en ese orden)

# ── Es siempre COPIA ────────────────────────────────────────────────
copia = M[[0, 1]]
copia[0, 0] = 999
print(M[0, 0])    # 10 — original no cambia

[[10 11 12]
 [30 31 32]
 [40 41 42]]
[[40 41 42]
 [20 21 22]
 [40 41 42]
 [10 11 12]]
[[11 12]
 [31 32]]
[[12 10]
 [22 20]
 [32 30]
 [42 40]]
10


3.5  Reshape — Cambio de Forma

In [ ]:
import numpy as np

v = np.arange(12)    # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# ── Reshape básico ─────────────────────────────────────────────────
M2x6  = v.reshape(2, 6)    # 2 filas, 6 columnas
M3x4  = v.reshape(3, 4)    # 3 filas, 4 columnas
M4x3  = v.reshape(4, 3)    # 4 filas, 3 columnas
M2x2x3= v.reshape(2, 2, 3) # tensor 3-D

# ── Uso de -1 (dimensión automática) ──────────────────────────────
auto = v.reshape(-1, 3)    # ?x3: NumPy calcula ? = 12/3 = 4 → shape (4,3)
print(auto.shape)          # (4, 3)

auto2 = v.reshape(2, -1)   # 2 x ?:  ? = 12/2 = 6 → shape (2, 6)
print(auto2.shape)         # (2, 6)

# ── flatten vs ravel ────────────────────────────────────────────────
M = v.reshape(3, 4)

flat  = M.flatten()   # siempre COPIA
rav   = M.ravel()     # VISTA si es posible

flat[0] = 999
print(M[0, 0])   # 0  → flatten no modifica el original

rav[0] = 777
print(M[0, 0])   # 777 → ravel SÍ modifica el original (es vista)

# ── Agregar dimensiones ─────────────────────────────────────────────
v1d = np.array([1, 2, 3, 4])   # shape (4,)
col = v1d.reshape(-1, 1)        # shape (4, 1) — vector columna
fil = v1d.reshape(1, -1)        # shape (1, 4) — vector fila
print(col.shape, fil.shape)

4.1  Operaciones Elemento a Elemento

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# ── Operaciones aritméticas básicas ────────────────────────────────
print(a + b)    # [11 22 33 44 55]   suma elemento a elemento
print(b - a)    # [ 9 18 27 36 45]   resta
print(a * b)    # [ 10  40  90 160 250]  multiplicación
print(b / a)    # [10. 10. 10. 10. 10.]  división (devuelve float)
print(a ** 2)   # [ 1  4  9 16 25]   potencia
print(b // 3)   # [ 3  6 10 13 16]   división entera
print(b % 3)    # [1 2 0 1 2]        módulo

# ── Operaciones con escalar (scalar broadcasting) ──────────────────
# El escalar se 'expande' para operar con cada elemento
print(a * 3)    # [ 3  6  9 12 15]
print(a + 100)  # [101 102 103 104 105]
print(a > 2)    # [False False  True  True  True]

# ── Matrices ───────────────────────────────────────────────────────
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])

print(M + N)    # [[6,8],[10,12]]  — suma elemento a elemento
print(M * N)    # [[ 5 12],[21 32]]  — producto elemento a elemento
# NOTA: M * N NO es el producto matricial. Para matrices usar M @ N

4.2  Broadcasting


In [ ]:
import numpy as np

# ── Escalar + vector (caso más simple) ─────────────────────────────
v = np.array([1, 2, 3, 4])   # shape (4,)
print(v + 10)                 # [11 12 13 14]  — escalar → (4,)

# ── Vector + matriz ────────────────────────────────────────────────
M = np.ones((3, 4))           # shape (3, 4)
v = np.array([10, 20, 30, 40])  # shape (4,)  → se convierte a (1,4) → (3,4)
print(M + v)
# [[11. 21. 31. 41.]
#  [11. 21. 31. 41.]
#  [11. 21. 31. 41.]]

# ── Columna + fila ─────────────────────────────────────────────────
col = np.array([[1], [2], [3]])    # shape (3, 1)
fil = np.array([10, 20, 30, 40])   # shape (4,)  → (1, 4)
suma = col + fil                    # shape (3, 4)
print(suma)
# [[11 21 31 41]
#  [12 22 32 42]
#  [13 23 33 43]]

# ── Normalización por columna (uso común en datos) ─────────────────
datos = np.random.randint(1, 100, (5, 3))
maximos = datos.max(axis=0)       # shape (3,)  — máximo de cada columna
norm = datos / maximos            # broadcasting (5,3) / (3,) → (5,3)
print(norm.round(2))

# ── Verificar compatibilidad ────────────────────────────────────────
# Shapes compatibles: (3,4) y (4,) → OK
# Shapes incompatibles: (3,4) y (3,) → Error (sin reshape)
try:
    err = np.ones((3,4)) + np.ones(3)
except ValueError as e:
    print('Error:', e)


4.3  Funciones Universales (ufuncs)

In [ ]:
import numpy as np

v = np.array([-4.5, -1.0, 0.0, 2.5, 9.0])

# ── Funciones básicas ──────────────────────────────────────────────
print(np.abs(v))       # [4.5 1.  0.  2.5 9. ]
print(np.sqrt(np.abs(v)))  # raíz cuadrada (abs para evitar NaN)
print(np.square(v))    # [20.25  1.   0.   6.25 81.  ]
print(np.floor(v))     # [-5. -1.  0.  2.  9.]  — redondeo hacia abajo
print(np.ceil(v))      # [-4. -1.  0.  3.  9.]  — redondeo hacia arriba

# ── Exponencial y logaritmo ─────────────────────────────────────────
pos = np.array([1.0, 2.0, 4.0, 8.0])
print(np.log(pos))     # ln: [0.    0.693 1.386 2.079]
print(np.log2(pos))    # log₂:[0. 1. 2. 3.]
print(np.exp(pos))     # e^x

# ── Trigonometría (argumentos en radianes) ──────────────────────────
angulos = np.linspace(0, 2 * np.pi, 5)   # 0, π/2, π, 3π/2, 2π
print(np.sin(angulos).round(4))   # [0. 1. 0. -1. -0.]
print(np.cos(angulos).round(4))   # [1. 0. -1. 0. 1.]

# ── clip — limitar valores a un rango ──────────────────────────────
datos = np.array([-10, -5, 0, 5, 10, 15, 20])
recortado = np.clip(datos, 0, 10)   # valores entre 0 y 10
print(recortado)  # [ 0  0  0  5 10 10 10]

# ── maximum / minimum elemento a elemento ──────────────────────────
a = np.array([3, 1, 7, 2])
b = np.array([4, 5, 2, 8])
print(np.maximum(a, b))   # [4 5 7 8]  — máximo entre pares
print(np.minimum(a, b))   # [3 1 2 2]  — mínimo entre pares

4.4  Estadística y Reducciones

In [ ]:
import numpy as np

M = np.array([[4,  7, 2, 8],
              [3, 11, 5, 1],
              [6,  9, 0, 4]])
# shape: (3, 4)  — 3 filas, 4 columnas

# ── Reducción global (todos los ejes) ──────────────────────────────
print(M.sum())     # 60
print(M.mean())    # 5.0
print(M.max())     # 11
# ── Reducción por eje ─────────────────────────────────────────────
print(M.sum(axis=0))    # suma por columna: [13 27  7 13]
print(M.sum(axis=1))    # suma por fila:    [21 20 19]
print(M.mean(axis=0))   # media de cada columna
print(M.max(axis=1))    # máximo de cada fila: [8 11 9]

# ── argmin / argmax — índice del extremo ───────────────────────────
print(M.argmin(axis=1))  # índice del mínimo en cada fila: [2 3 2]
print(M.argmax(axis=0))  # índice del máximo en cada columna: [2 1 1 0]

# ── std y var ──────────────────────────────────────────────────────
print(M.std())           # desviación estándar global
print(M.var(axis=0))     # varianza de cada columna

# ── keepdims — mantener dimensiones ────────────────────────────────
media = M.mean(axis=0, keepdims=True)   # shape (1, 4) en vez de (4,)
print(media.shape)                       # (1, 4)
centrado = M - media                     # broadcasting funciona directamente

# ── cumsum — suma acumulada ─────────────────────────────────────────
v = np.array([1, 2, 3, 4, 5])
print(np.cumsum(v))    # [1  3  6 10 15]

# ── percentile ──────────────────────────────────────────────────────
print(np.percentile(M, 25))   # percentil 25 (primer cuartil)
print(np.median(M))           # mediana (equivale a percentil 50)

4.5  Concatenación y Apilamiento de Arrays

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7,  8,  9],
              [10, 11, 12]])

# ── concatenate ────────────────────────────────────────────────────
vertical   = np.concatenate([A, B], axis=0)   # apilar filas
print(vertical.shape)    # (4, 3)

horizontal = np.concatenate([A, B], axis=1)   # apilar columnas
print(horizontal.shape)  # (2, 6)

# ── vstack y hstack ─────────────────────────────────────────────────
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.vstack([v1, v2]))   # [[1 2 3], [4 5 6]]  → shape (2,3)
print(np.hstack([v1, v2]))   # [1 2 3 4 5 6]       → shape (6,)

# ── stack — crea nuevo eje ──────────────────────────────────────────
capas = np.stack([A, B], axis=0)    # shape (2, 2, 3) — nuevo eje al frente
print(capas.shape)

# ── split ───────────────────────────────────────────────────────────
M = np.arange(1, 25).reshape(4, 6)
partes = np.split(M, 2, axis=1)     # divide en 2 a lo largo de columnas
print(partes[0].shape)   # (4, 3)
print(partes[1].shape)   # (4, 3)

filas = np.vsplit(M, 4)             # divide en 4 filas individuales
print(filas[0])    # primera fila

4.6  Ordenamiento y Búsqueda

In [ ]:
import numpy as np

v = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])

# ── sort ────────────────────────────────────────────────────────────
ordenado = np.sort(v)          # copia — v no cambia
v.sort()                       # in-place — v ahora está ordenado

# ── argsort ─────────────────────────────────────────────────────────
v = np.array([5, 2, 8, 1, 9, 3])
idx = np.argsort(v)            # [3 1 5 0 2 4] — índices que ordenarían v
print(v[idx])                  # [1 2 3 5 8 9]

# Reordenar dos arrays en paralelo
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas   = np.array([75, 92, 88, 61, 95, 78])
orden = np.argsort(notas)[::-1]    # índices de mayor a menor
print(nombres[orden])              # ['Eva' 'Ana' 'Diana' 'Luis' 'Carlos' 'Pedro']
print(notas[orden])                # [95 92 88 78 75 61]

# ── np.where con 1 argumento — posiciones de True ──────────────────
datos = np.array([0, 5, 0, 3, 0, 8])
pos = np.where(datos > 0)    # devuelve tupla de arrays de índices
print(pos)          # (array([1, 3, 5]),)
print(datos[pos])   # [5 3 8]

# ── unique ───────────────────────────────────────────────────────────
colores = np.array([1, 2, 1, 3, 2, 1, 4, 3])
unicos, conteos = np.unique(colores, return_counts=True)
print(unicos)   # [1 2 3 4]
print(conteos)  # [3 2 2 1]